version: '3.8'

services:
  taxipickme:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxipickme-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=http://taxipickme.com
    networks:
      - taxipickme-network

networks:
  taxipickme-network:
    driver: bridge
