version: '3.8'

services:
  taxisrilanka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxisrilanka-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=http://taxisrilanka.com
    networks:
      - taxisrilanka-network

networks:
  taxisrilanka-network:
    driver: bridge
